name: Assign issue

on:
  issues:
    types: [ opened ]

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }
          assignees: wine
